source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'sqlite3'
gem 'devise'
gem 'rails_admin', :git => 'git://github.com/sferik/rails_admin.git'
gem 'jquery-rails', '>= 1.0.12'
gem 'awesome_nested_set'
gem 'friendly_id', '~> 3.2'
gem 'i18n_routing', '~> 0.4.8'
gem 'breadcrumbs', '0.1.6'
gem 'meta-tags', '1.2.4', :require => 'meta_tags'
